export const workManagementBoardsVisualMigrationSystem = Object.freeze({
  milestone: 'M84',
  stage: 'I',
  title: 'Boards Visual Migration',
  baselineMilestone: 'M83',
  migrationModel: 'presentation-only-board-successor',
  semanticsVersion: '1.43.2-m84-v1',
  migratedSurfaces: Object.freeze([
    'boards-shell',
    'boards-collection',
    'board-views',
    'board-table-grid-list',
    'board-cards',
    'board-statuses',
    'board-filters',
    'board-dialogs',
    'board-kanban',
    'item-workspace',
  ] as const),
  preservedAuthorities: Object.freeze({
    boardsCollectionAndRoutes: 'M45',
    backendAndDataContract: 'M46',
    tableGroupItemBehavior: 'M47',
    columnsCellsAndStatuses: 'M48',
    kanbanAndDragDrop: 'M49',
    richItemWorkspace: 'M50',
    realtimeAndConcurrency: 'M51',
    crossModuleRbac: 'M52',
    priorBoardDesignSystemMigration: 'M73',
  }),
  invariants: Object.freeze({
    presentationOnlySuccessor: true,
    preservesBoardDomainState: true,
    preservesPersistenceSemantics: true,
    preservesRealtimeSemantics: true,
    preservesRbacSemantics: true,
    preservesDragDropSemantics: true,
    preservesHistoryAndSelectionSemantics: true,
    preservesStatusIdentifiers: true,
    preservesLegacyRuntimeHooks: true,
    preservesBoardRepositoryContracts: true,
    preservesSupabaseContracts: true,
    noSchemaMigrationRequired: true,
    noBackendMutationRequired: true,
  }),
});

export type WorkManagementBoardsVisualSurface = typeof workManagementBoardsVisualMigrationSystem.migratedSurfaces[number];
