/** Product-facing references to governed Work Management CSS custom properties. */
export const workManagementTokens = Object.freeze({
  semantic: Object.freeze({
    color: Object.freeze({
      canvas: 'var(--wm-color-canvas)',
      surface: 'var(--wm-color-surface-primary)',
      subtleSurface: 'var(--wm-color-surface-secondary)',
      mutedSurface: 'var(--wm-color-surface-tertiary)',
      raisedSurface: 'var(--wm-color-surface-elevated)',
      selectedSurface: 'var(--wm-color-surface-selected)',
      text: 'var(--wm-color-text-primary)',
      mutedText: 'var(--wm-color-text-secondary)',
      border: 'var(--wm-color-border-primary)',
      subtleBorder: 'var(--wm-color-border-subtle)',
      strongBorder: 'var(--wm-color-border-strong)',
      accent: 'var(--wm-color-accent)',
      accentSoft: 'var(--wm-color-accent-soft)',
      accentContrast: 'var(--wm-color-accent-contrast)',
      positive: 'var(--wm-color-positive)',
      negative: 'var(--wm-color-negative)',
      warning: 'var(--wm-color-warning)',
      info: 'var(--wm-color-info)',
      focus: 'var(--wm-color-focus)',
    }),
    spacing: Object.freeze({
      cluster: 'var(--wm-semantic-space-cluster)',
      control: 'var(--wm-semantic-space-control)',
      section: 'var(--wm-semantic-space-section)',
      separation: 'var(--wm-semantic-space-separation)',
      containment: 'var(--wm-semantic-space-containment)',
    }),
    control: Object.freeze({
      compact: 'var(--wm-semantic-control-compact)',
      default: 'var(--wm-semantic-control-default)',
      comfortable: 'var(--wm-semantic-control-comfortable)',
      hitTarget: 'var(--wm-semantic-hit-target)',
    }),
    sizing: Object.freeze({
      iconXs: 'var(--wm-semantic-size-icon-xs)',
      iconSm: 'var(--wm-semantic-size-icon-sm)',
      iconMd: 'var(--wm-semantic-size-icon-md)',
      iconLg: 'var(--wm-semantic-size-icon-lg)',
      iconXl: 'var(--wm-semantic-size-icon-xl)',
      panelNarrow: 'var(--wm-semantic-size-panel-narrow)',
      panelMedium: 'var(--wm-semantic-size-panel-medium)',
      panelWide: 'var(--wm-semantic-size-panel-wide)',
    }),
    density: Object.freeze({
      compactSpace: 'var(--wm-semantic-density-space-compact)',
      defaultSpace: 'var(--wm-semantic-density-space-default)',
      comfortableSpace: 'var(--wm-semantic-density-space-comfortable)',
      compactControl: 'var(--wm-semantic-density-control-compact)',
      defaultControl: 'var(--wm-semantic-density-control-default)',
      comfortableControl: 'var(--wm-semantic-density-control-comfortable)',
    }),
    surface: Object.freeze({
      controlRadius: 'var(--wm-semantic-radius-control)',
      surfaceRadius: 'var(--wm-semantic-radius-surface)',
      raisedShadow: 'var(--wm-semantic-shadow-raised)',
      overlayShadow: 'var(--wm-semantic-shadow-overlay)',
      focusWidth: 'var(--wm-semantic-focus-width)',
      borderHairline: 'var(--wm-semantic-border-hairline)',
      borderStrong: 'var(--wm-semantic-border-strong)',
      blurSubtle: 'var(--wm-semantic-blur-subtle)',
      blurSurface: 'var(--wm-semantic-blur-surface)',
      blurOverlay: 'var(--wm-semantic-blur-overlay)',
      elevationFlat: 'var(--wm-semantic-elevation-flat)',
      elevationRest: 'var(--wm-semantic-elevation-rest)',
      elevationFloating: 'var(--wm-semantic-elevation-floating)',
    }),
    motion: Object.freeze({
      fast: 'var(--wm-semantic-motion-fast)',
      standard: 'var(--wm-semantic-motion-standard)',
      deliberate: 'var(--wm-semantic-motion-deliberate)',
      enterEase: 'var(--wm-semantic-ease-enter)',
      exitEase: 'var(--wm-semantic-ease-exit)',
      standardEase: 'var(--wm-semantic-ease-standard)',
    }),
    breakpoint: Object.freeze({
      narrow: 'var(--wm-semantic-breakpoint-narrow)',
      tablet: 'var(--wm-semantic-breakpoint-tablet)',
      laptop: 'var(--wm-semantic-breakpoint-laptop)',
      wide: 'var(--wm-semantic-breakpoint-wide)',
    }),
    layer: Object.freeze({
      base: 'var(--wm-semantic-z-base)',
      sticky: 'var(--wm-semantic-z-sticky)',
      floating: 'var(--wm-semantic-z-floating)',
      drawer: 'var(--wm-semantic-z-drawer)',
      modal: 'var(--wm-semantic-z-modal)',
      command: 'var(--wm-semantic-z-command)',
      toast: 'var(--wm-semantic-z-toast)',
    }),
  }),
  componentNamespace: Object.freeze({
    shell: '--wm-shell-',
    board: '--wm-board-',
  }),
} as const);

export type WorkManagementTokenReferences = typeof workManagementTokens;
