import React from 'react'; import { Command as CommandPrimitive } from 'cmdk'; import { Search } from 'lucide-react'; import { cn } from '@material/lib/utils'; import { Dialog, DialogContent } from './dialog';
export const Command=React.forwardRef(({className,...p},r)=><CommandPrimitive ref={r} className={cn('flex h-full w-full flex-col overflow-hidden rounded-md bg-popover text-popover-foreground',className)} {...p}/>); Command.displayName='Command';
export function CommandDialog({children,...props}){return <Dialog {...props}><DialogContent className='overflow-hidden p-0 shadow-lg'><Command className='[&_[cmdk-group-heading]]:px-2 [&_[cmdk-group-heading]]:font-medium [&_[cmdk-group-heading]]:text-muted-foreground'>{children}</Command></DialogContent></Dialog>}
export const CommandInput=React.forwardRef(({className,...p},r)=><div className='flex items-center border-b px-3' cmdk-input-wrapper=''><Search className='mr-2 h-4 w-4 shrink-0 opacity-50'/><CommandPrimitive.Input ref={r} className={cn('flex h-11 w-full rounded-md bg-transparent py-3 text-sm outline-none placeholder:text-muted-foreground disabled:cursor-not-allowed disabled:opacity-50',className)} {...p}/></div>); CommandInput.displayName='CommandInput';
export const CommandList=React.forwardRef(({className,...p},r)=><CommandPrimitive.List ref={r} className={cn('max-h-[300px] overflow-y-auto overflow-x-hidden',className)} {...p}/>); CommandList.displayName='CommandList';
export const CommandEmpty=React.forwardRef((p,r)=><CommandPrimitive.Empty ref={r} className='py-6 text-center text-sm' {...p}/>); CommandEmpty.displayName='CommandEmpty';
export const CommandGroup=React.forwardRef(({className,...p},r)=><CommandPrimitive.Group ref={r} className={cn('overflow-hidden p-1 text-foreground [&_[cmdk-group-heading]]:px-2 [&_[cmdk-group-heading]]:py-1.5 [&_[cmdk-group-heading]]:text-xs [&_[cmdk-group-heading]]:font-medium [&_[cmdk-group-heading]]:text-muted-foreground',className)} {...p}/>); CommandGroup.displayName='CommandGroup';
export const CommandSeparator=React.forwardRef(({className,...p},r)=><CommandPrimitive.Separator ref={r} className={cn('-mx-1 h-px bg-border',className)} {...p}/>); CommandSeparator.displayName='CommandSeparator';
export const CommandItem=React.forwardRef(({className,...p},r)=><CommandPrimitive.Item ref={r} className={cn('relative flex cursor-default select-none items-center rounded-sm px-2 py-1.5 text-sm outline-none data-[selected=true]:bg-accent data-[selected=true]:text-accent-foreground data-[disabled=true]:pointer-events-none data-[disabled=true]:opacity-50',className)} {...p}/>); CommandItem.displayName='CommandItem';
export function CommandShortcut({className,...p}){return <span className={cn('ml-auto text-xs tracking-widest text-muted-foreground',className)} {...p}/>}
