export const layoutGridSpatialSystem = Object.freeze({
  milestone: 61,
  stage: 'H',
  spatialAuthority: 'assets/css/foundation/layout-system.css',
  primitiveAuthority: 'src/design-system/primitives/layout.tsx',
  typedContract: 'src/design-system/layout-system.ts',
  spacingScaleAuthority: 'assets/css/foundation/tokens.css',
  semanticTokenAuthority: 'assets/css/foundation/token-architecture.css',
  spatialRoles: Object.freeze(['tight','compact','control','standard','section','major'] as const),
  contentWidths: Object.freeze(['content','reading','full'] as const),
  gridColumns: Object.freeze([1,2,3] as const),
  layoutPrimitives: Object.freeze(['WMStack','WMCluster','WMGrid','WMPage','WMSection','WMContainer'] as const),
  policies: Object.freeze({
    semanticAliasesMustResolveThroughCertifiedTokens: true,
    zeroImplicitBreakpointBehavior: true,
    minWidthZeroOnComposableLayoutPrimitives: true,
    existingPrimitiveDefaultsRemainVisuallyEquivalent: true,
    noShellGeometryRewriteInM61: true,
    noBoardGeometryRewriteInM61: true,
    noModuleLayoutRewriteInM61: true,
    noResponsiveBreakpointChangesInM61: true,
  }),
  successorBoundaries: Object.freeze({
    responsiveArchitecture: 62,
    accessibilityFoundation: 63,
    componentConsolidation: 64,
    hostMigration: 72,
    boardsMigration: 73,
    timeTrackerMigration: 74,
    fuelTrackMigration: 75,
    tradeLinkMigration: 76,
  }),
});
export type WorkManagementSpatialRole = typeof layoutGridSpatialSystem.spatialRoles[number];
