export const responsiveArchitecture = Object.freeze({
  milestone: 62,
  stage: 'H',
  responsiveAuthority: 'assets/css/foundation/responsive-system.css',
  typedContract: 'src/design-system/responsive-system.ts',
  primitiveAuthority: 'src/design-system/primitives/layout.tsx',
  breakpointTokenAuthority: 'assets/css/foundation/tokens.css',
  breakpoints: Object.freeze({ narrow: 640, tablet: 840, laptop: 1120, wide: 1440 }),
  adaptivePrimitives: Object.freeze(['WMGrid.collapseAt', 'WMCluster.stackAt', 'WMPage.sharedGutter'] as const),
  policies: Object.freeze({
    sharedResponsiveQueriesUseCertifiedBreakpointEquivalents: true,
    sharedResponsiveQueriesUseRemUnits: true,
    adaptiveBehaviorIsExplicitOptIn: true,
    noImplicitContentHiding: true,
    preserveExistingPrimitiveDefaults: true,
    preserveExistingFeatureAndModuleBreakpointsUntilMigration: true,
    noShellResponsiveRewriteInM62: true,
    noBoardResponsiveRewriteInM62: true,
    noModuleResponsiveRewriteInM62: true,
  }),
  compatibilityAuthorities: Object.freeze([
    'assets/css/app.css',
    'assets/css/boards-monday.css',
    'apps/time-tracker/styles.css',
    'apps/time-tracker/v2.css',
    'apps/fueltrack-plus/styles.v3.17.0-wm6.css',
    'apps/tradelink/styles.v1.42.0-wm1.css',
  ] as const),
  successorBoundaries: Object.freeze({
    accessibilityFoundation: 63,
    componentConsolidation: 64,
    hostMigration: 72,
    boardsMigration: 73,
    timeTrackerMigration: 74,
    fuelTrackMigration: 75,
    tradeLinkMigration: 76,
  }),
});
export type WorkManagementResponsiveBreakpoint = keyof typeof responsiveArchitecture.breakpoints;
