export const STAGE_E_M22_NORMALIZED_MODULE_DATA_TARGET = Object.freeze({
  milestone: 'Stage E Milestone 22 — Normalized module data foundation',
  prerequisite: Object.freeze({ milestone: 'M21', state: 'active-certified' }),
  activationState: 'active-certified',
  architectureVersion: 30,
  registryAuthority: 'config/modules.ts',
  contractAuthority: 'src/platform/contracts/normalized-module-data.ts',
  schemaAuthority: 'src/runtime-schemas/normalized-module-data.ts',
  serviceAuthority: 'assets/js/platform/data/normalized-module-data-service.ts',
  persistenceAuthority: 'existing-supabase-module-state-rpcs',
  compatibilityModuleStore: 'assets/js/core/module-cloud-store.ts',
  moduleIds: Object.freeze(['time-tracker', 'fueltrack-plus', 'tradelink']),
  malformedStatePolicy: 'surface-invalid-without-silent-repair',
  unmappedStatePolicy: 'preserve-and-surface-unmapped',
  expectedRevisionConcurrency: true,
  legacyKeyCompatibility: true,
  iframeReplacementRequired: false,
  newExternalDependency: false,
  supabaseMigrationRequired: false,
} as const);
