export const STAGE_D_M20_BOARD_COLLABORATIVE_REALTIME_TARGET = Object.freeze({
  milestone: 'Stage D Milestone 20 — Board collaborative Realtime',
  prerequisite: Object.freeze({ milestone: 'M19', state: 'active-certified' }),
  activationState: 'active-certified',
  architectureVersion: 28,
  transportAuthority: 'assets/js/platform/data/supabase-realtime-client.ts',
  serviceAuthority: 'assets/js/features/boards/services/board-realtime-service.ts',
  controllerAuthority: 'assets/js/features/boards/controllers/board-realtime-controller.ts',
  boardEngine: 'assets/js/boards-ui.ts',
  databaseMigration: 'supabase/migrations/v1.43.2-stage-d-m20-board-collaborative-realtime.sql',
  collaborationModel: 'private-database-broadcast-plus-presence-authorized-rpc-refetch',
  topicPattern: 'board:<uuid>',
  changeEvent: 'board-change',
  canonicalStateAuthority: 'typed-board-repository-rpc',
  realtimePayloadPolicy: 'metadata-only',
  fallbackPolicy: Object.freeze({ mode: 'poll-while-degraded', intervalMs: 30000 }),
  reconnectPolicy: Object.freeze({ delaysMs: Object.freeze([1000, 2000, 5000, 10000]), heartbeatMs: 20000, tokenRefreshMs: 240000 }),
  presence: true,
  directPostgresChanges: false,
  externalRealtimeDependencyInstalled: false,
  supabaseMigrationRequired: true,
} as const);
