export const STAGE_D_M21_RICH_ITEM_WORKSPACE_TARGET = Object.freeze({
  milestone: 'Stage D Milestone 21 — Rich Item Workspace',
  prerequisite: Object.freeze({ milestone: 'M20', state: 'active-certified' }),
  activationState: 'active-certified',
  architectureVersion: 29,
  viewAuthority: 'assets/js/features/boards/views/item-workspace-view.ts',
  controllerAuthority: 'assets/js/features/boards/controllers/item-workspace-controller.ts',
  runtimeAuthority: 'assets/js/features/boards/services/item-workspace-runtime.ts',
  stateAuthority: 'src/features/boards/contracts/view-state.ts',
  commandAuthority: 'assets/js/features/boards/services/board-command-service.ts',
  canonicalStateAuthority: 'typed-board-repository-rpc',
  tabs: Object.freeze(['overview', 'updates', 'files', 'activity']),
  explicitPropertySave: true,
  saveOnBlur: false,
  updateDraftResilience: true,
  attachmentDragDrop: true,
  realtimeConvergence: 'm20-authorized-refetch',
  newExternalDependency: false,
  supabaseMigrationRequired: false,
} as const);
