export type M36ActivationState =
  | 'implementation-complete-pending-certification'
  | 'active-pending-release-certification'
  | 'active-certified';

export const stageFM36ProductionCutoverCertificationTarget = Object.freeze({
  milestone: 36,
  stage: 'F',
  name: 'Production cutover certification',
  activationState: 'active-certified' as M36ActivationState,
  prerequisite: Object.freeze({ milestone: 35, requiredState: 'active-certified' as const }),
  architectureVersion: 44,
  authority: Object.freeze({
    policy: 'config/production-cutover-policy.json',
    verifier: 'verify-stage-f-m36-production-cutover-certification.mjs',
    executionVerifier: 'scripts/verify-production-cutover-execution.mjs',
    artifactVerifier: 'scripts/verify-production-cutover-artifact.mjs',
    evidenceGenerator: 'scripts/generate-production-cutover-evidence.mjs',
    activator: 'scripts/activate-stage-f-m36.mjs',
    certifier: 'scripts/certify-stage-f-m36.sh',
    workflow: '.github/workflows/production-cutover.yml',
    deploymentWorkflow: '.github/workflows/deploy-pages.yml',
    runbook: 'docs/WORK-MANAGEMENT-PRODUCTION-CUTOVER.md',
  }),
  artifactValidation: Object.freeze({
    sourceEntryPolicy: 'executable-reference-only-v2' as const,
    allowBundledSourceIdentityMetadata: true,
    forbidExecutableSourceEntryReferences: true,
    developmentHostPolicy: 'network-resource-reference-only-v2' as const,
    allowLocalhostValidationMetadata: true,
    forbidExecutableDevelopmentHostReferences: true,
    forbidViteDevelopmentClientReferences: true,
  }),
  certification: Object.freeze({
    fullReleaseGateRequired: true,
    cleanLockfileInstallRequired: true,
    historicalRegressionRequired: true,
    modernCoverageRequired: true,
    playwrightRequired: true,
    boundedCdpParityRequired: true,
    databaseRlsLocalRequired: true,
    productionBuildRequired: true,
    distVerificationRequired: true,
    previewVerificationRequired: true,
    performanceBudgetsRequired: true,
    serviceWorkerArtifactRequired: true,
    dependencyAuditRequired: true,
    sourceSecretScanRequired: true,
    distOnlyDeploymentRequired: true,
    artifactSha256ManifestRequired: true,
    provenanceRecordRequired: true,
    postDeployHttpSmokeRequired: true,
    rollbackBaselineRequired: true,
  }),
  productionBoundaries: Object.freeze([
    Object.freeze({ id: 'm26-module-iframes', status: 'certified-live-compatibility' as const, reason: 'TimeTracker, FuelTrack+, and TradeLink remain same-origin iframe islands until their native retirement gates are independently satisfied.' }),
    Object.freeze({ id: 'm28-edge-function-cutover', status: 'deployment-dependent-retained-rpc-authority' as const, reason: 'The protected user-management RPC remains authoritative until admin-sync-auth-access is externally deployed with server-only secrets and separately enabled; M36 must not make the browser depend on an undeployed function.' }),
    Object.freeze({ id: 'm30-bounded-cdp', status: 'certified-parity-backstop' as const, reason: 'Playwright is the modern browser-test layer while bounded CDP remains a required release parity backstop for this cutover.' }),
    Object.freeze({ id: 'm34-provider-backup-and-encrypted-retention', status: 'external-operational-prerequisite' as const, reason: 'Provider backup/PITR and encrypted off-client recovery-package retention are infrastructure/operator responsibilities and must be evidenced outside the static repository.' }),
  ]),
  externalOperationalPrerequisites: Object.freeze([
    'GitHub Pages production environment is configured and the deployment workflow has pages:write/id-token:write.',
    'VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY are configured as public repository/environment variables only.',
    'Supabase Auth Site URL and Redirect URLs match the deployed HTTPS GitHub Pages base URL.',
    'A last-known-good certified source ZIP SHA-256 and corresponding production dist artifact are retained before promotion.',
    'Provider-level database backup/PITR and approved encrypted backup retention have current operator evidence.',
  ]),
  rollback: Object.freeze({
    strategy: 'redeploy-last-known-good-certified-dist-v1',
    destructiveDatabaseRollbackAutomatic: false,
    sourceBaselineShaRequired: true,
    distArtifactRetentionRequired: true,
    recoveryCheckpointRequiredForDataRestore: true,
  }),
  databaseChanges: Object.freeze({ migrationRequired: false, schemaChangeRequired: false, productionDataRewriteRequired: false }),
});
