export const stageGM38RuntimeConfigurationBackendPreflightTarget = Object.freeze({
  stage: 'G' as const,
  milestone: 38 as const,
  name: 'Runtime Configuration & Backend Capability Preflight',
  architectureVersion: 46 as const,
  activationState: 'active-certified' as const,
  prerequisite: Object.freeze({ stage:'G' as const, milestone:37 as const, requiredState:'active-certified' as const }),
  scope: Object.freeze([
    'environment-separated public Supabase runtime configuration',
    'authenticated non-destructive backend capability report',
    'RPC/table/private-storage/private-Realtime capability verification',
    'module-specific fail-closed route gating with explicit diagnostics',
    'local/development/CI/production configuration verification',
  ]),
  authorities: Object.freeze({
    manifest:'config/backend-capability-manifest.ts',
    policy:'config/runtime-backend-preflight-policy.json',
    runtime:'assets/js/platform/data/backend-capability-preflight.ts',
    contract:'src/platform/contracts/backend-capability-preflight.ts',
    runtimeConfig:'config/vite-runtime-config.ts',
    databaseMigration:'supabase/migrations/v1.43.2-stage-g-m38-runtime-capability-preflight.sql',
    databaseRpc:'public.wm_runtime_capabilities',
    verifier:'verify-stage-g-m38-runtime-configuration-backend-preflight.mjs',
    executionVerifier:'scripts/verify-runtime-backend-preflight-execution.mjs',
    browserRunner:'scripts/run-backend-capability-preflight-browser.mjs',
    environmentVerifier:'scripts/verify-runtime-backend-config.mjs',
    activator:'scripts/activate-stage-g-m38.mjs',
    certifier:'scripts/certify-stage-g-m38.sh',
    workflow:'.github/workflows/backend-capability-preflight.yml',
    runbook:'docs/WORK-MANAGEMENT-RUNTIME-BACKEND-PREFLIGHT.md',
  }),
  retainedBoundaries: Object.freeze([
    'M26 same-origin iframe islands remain for TimeTracker, FuelTrack+, and TradeLink.',
    'M28 protected RPC authority remains until the Edge Function receives separate production cutover.',
    'M30 bounded-CDP parity remains beside Playwright.',
    'M34 provider backup/PITR remains an external operational control.',
    'M37 characterized Account/Users/Settings/Boards functional regressions remain open for M39+ remediation.',
  ]),
  completionCriteria: Object.freeze([
    'Checked-in backend configuration contains no deployment-specific Supabase project fallback.',
    'Vite configuration never combines one environment-provided credential with another fallback credential.',
    'Runtime preflight verifies the exact required resource classes through an authenticated non-destructive RPC.',
    'Board Storage is verified private and Board Realtime authorization/policies/broadcast triggers are present.',
    'Each backend-dependent module is gated independently until its own capability requirements pass.',
    'Configuration, health, authentication, missing-contract, schema-version, and capability-mismatch failures render explicit diagnostics.',
    'M37 browser fixture remains compatible with the M38 gate.',
    'Dedicated M38 browser tests prove ready, missing-capability, schema-mismatch, and missing-contract behavior.',
  ]),
  productionReadiness: 'not-yet-functional-recovery-continues' as const,
});
