export const STAGE_H_M58_DESIGN_TOKEN_ARCHITECTURE_TARGET = Object.freeze({
  milestone: 58,
  stage: 'H',
  release: '1.43.2',
  semanticsVersion: '1.43.2-m58-v1',
  scope: 'design-token-architecture-consolidation',
  activationState: 'active-certified',
  failClosed: true,
  canonicalTokenArchitecture: 'config/design-token-architecture.ts',
  canonicalSemanticAliasLayer: 'assets/css/foundation/token-architecture.css',
  productTokenReferences: 'src/design-system/tokens.ts',
  governanceDocumentation: 'architecture/ui-governance/design-token-architecture.md',
  baselineSnapshot: 'regression-baseline/m58-design-token-architecture.json',
  requiredStaticGate: 'design-tokens:check',
  requiredDeterministicGate: 'design-tokens:test',
  requiredBrowserGate: 'design-tokens:browser',
  requiredCertificationGate: 'design-tokens:certify',
  requiredHistoricalGate: 'verify:historical-all',
  certifiedArtifactDirectory: 'm58-certified-artifacts-upload',
  certifiedBaseline: 'Work-Management-App-v1.43.2-Stage-H-M58-Certified-Baseline.zip',
  visualValueChangeAllowed: false,
  existingConsumerRewriteRequired: false,
} as const);
