export const stageIM97WorkspaceWideVisualRegressionFunctionalPreservationTarget = Object.freeze({
  milestone: 97,
  stage: 'I',
  release: '1.43.2',
  name: 'Workspace-Wide Visual Regression & Functional Preservation',
  semanticsVersion: '1.43.2-m97-v1',
  activationState: 'active-certified',
  failClosed: true,
  prerequisite: Object.freeze({
    milestone: 96,
    certifiedZipSha256: '300d769769b27353cd08cf9e83ce2e96ab39ccb50c5e4940e0fb79ddee4701d2',
    certifiedSourceSha256: '26d0d6e9950fbe71d45d1df244ad56975b4f3092354212fd66af70b7bc82062a',
  }),
  scope: Object.freeze([
    'cross-browser-cross-viewport-workspace-matrix',
    'host-account-settings-users-boards-visual-contracts',
    'time-tracker-fueltrack-plus-tradelink-visual-contracts',
    'screenshot-evidence-with-cryptographic-manifest',
    'authenticated-functional-preservation',
    'cross-module-rbac-preservation',
    'module-runtime-stabilization-preservation',
    'historical-regression-and-release-gate-preservation',
    'prove-no-application-behavior-source-mutation-in-m97',
  ]),
  browserMatrix: Object.freeze(['chromium', 'firefox', 'webkit']),
  viewports: Object.freeze([
    Object.freeze({ id: 'mobile', width: 390, height: 844 }),
    Object.freeze({ id: 'tablet', width: 768, height: 1024 }),
    Object.freeze({ id: 'laptop', width: 1366, height: 768 }),
    Object.freeze({ id: 'desktop', width: 1440, height: 900 }),
  ]),
  hostRoutes: Object.freeze(['account', 'settings', 'users', 'boards']),
  embeddedModules: Object.freeze(['time-tracker', 'fueltrack-plus', 'tradelink']),
  expectedScreenshotEvidenceCount: 84,
  visualContractPolicy: Object.freeze({
    pixelPerfectCrossEngineEqualityRequired: false,
    rationale: 'Cross-engine rasterization is not a stable semantic contract; screenshots are retained as evidence while deterministic layout, containment, identity, accessibility, and behavior contracts are asserted.',
    screenshotsRequired: true,
    screenshotManifestSha256Required: true,
    horizontalOverflowForbidden: true,
    authenticatedIdentityRequired: true,
  }),
  boundaries: Object.freeze({
    noApplicationSourceMutation: true,
    noDatabaseSchemaMutation: true,
    noMigrationMutation: true,
    noBackendApiMutation: true,
    noAuthenticationAuthorizationMutation: true,
    noPersistenceMutation: true,
    noRouteOwnershipMutation: true,
    noModuleBusinessLogicMutation: true,
    noVisualFeatureMutation: true,
  }),
  outputDirectory: 'm97-continuation-artifacts-upload',
  evidenceDirectory: 'm97-browser-evidence',
  continuationBaseline: 'Work-Management-App-v1.43.2-Stage-I-M97-Implementation-Complete-Verification-Pending.zip',
} as const);
