export type M33ActivationState = 'implementation-complete-pending-certification' | 'active-pending-release-certification' | 'active-certified';
export const stageFM33ServiceWorkerUpdateStrategyTarget = Object.freeze({
  milestone: 33,
  stage: 'F',
  name: 'Service worker / update strategy',
  activationState: 'active-certified' as M33ActivationState,
  prerequisite: Object.freeze({ milestone: 32, requiredState: 'active-certified' as const }),
  architectureVersion: 41,
  authority: Object.freeze({
    serviceWorker: 'service-worker.js',
    runtimeAssetManifest: 'config/runtime-assets.js',
    clientCoordinator: 'assets/js/platform/update/service-worker-update.ts',
    contract: 'src/platform/contracts/service-worker-update.ts',
    buildManifestGenerator: 'scripts/lib/service-worker-build-manifest.mjs',
    buildIntegration: 'vite.config.js',
    executionVerifier: 'scripts/verify-service-worker-update-execution.mjs',
    verifier: 'verify-stage-f-m33-service-worker-update-strategy.mjs',
  }),
  strategy: Object.freeze({
    activation: 'explicit-user-controlled-v1',
    cacheIdentity: 'deterministic-build-scoped-v1',
    updateViaCache: 'none' as const,
    updateCheckTriggers: Object.freeze(['visibility', 'online'] as const),
    minimumUpdateCheckIntervalMs: 300_000,
    multiTabConvergence: 'controllerchange-reload-existing-clients-v1',
    navigation: 'network-first-navigation-preload-offline-shell-v1',
    hashedAssets: 'current-build-cache-first-v1',
    mutableSharedRuntime: 'network-first-current-build-fallback-v1',
    embeddedApplications: 'network-authoritative-no-store-v1',
    sensitiveRequests: 'network-only-no-store-v1',
    staleCacheCleanup: true,
  }),
  compatibilityBoundaries: Object.freeze([
    Object.freeze({ id: 'legacy-skip-waiting-message', status: 'temporary-compatibility-alias' as const, reason: 'M32 clients send SKIP_WAITING; the M33 worker accepts that message for one migration cycle alongside WM_ACTIVATE_UPDATE.' }),
    Object.freeze({ id: 'embedded-app-offline-policy', status: 'network-authoritative' as const, reason: 'TimeTracker, FuelTrack+, and TradeLink remain M26 compatibility islands and are not silently served from stale cached business-runtime assets.' }),
    Object.freeze({ id: 'unsaved-cross-tab-work', status: 'explicit-update-reloads-controlled-tabs' as const, reason: 'User-triggered activation converges controlled tabs by reload; application workflows must continue persisting edits before update activation.' }),
  ]),
  databaseChanges: Object.freeze({ migrationRequired: false, schemaChangeRequired: false, productionDataRewriteRequired: false }),
});
