export type M32ActivationState = 'implementation-complete-pending-certification' | 'active-pending-release-certification' | 'active-certified';
export const stageFM32ObservabilityTarget = Object.freeze({
  milestone: 32,
  stage: 'F',
  name: 'Observability',
  activationState: 'active-certified' as M32ActivationState,
  prerequisite: Object.freeze({ milestone: 31, requiredState: 'active-certified' as const }),
  architectureVersion: 40,
  authority: Object.freeze({
    contract: 'src/platform/contracts/observability.ts',
    runtime: 'assets/js/platform/observability/observability.ts',
    browserInstrumentation: 'assets/js/platform/observability/browser-observer.ts',
    optionalTransport: 'assets/js/platform/observability/beacon-transport.ts',
    diagnosticsBridge: 'assets/js/platform/observability/diagnostics.ts',
    executionVerifier: 'scripts/verify-observability-execution.mjs',
    verifier: 'verify-stage-f-m32-observability.mjs',
  }),
  signals: Object.freeze(['log', 'counter', 'histogram', 'span', 'exception', 'performance'] as const),
  privacy: Object.freeze({
    memoryFirst: true,
    persistentClientStorage: false,
    sensitiveKeyRedaction: true,
    tokenPatternRedaction: true,
    emailPatternRedaction: true,
    uuidPathRedaction: true,
    maxBufferRecords: 240,
    exportSampleRate: 0.2,
    warningAndErrorAlwaysSampled: true,
  }),
  tracing: Object.freeze({
    traceIdBytes: 16,
    spanIdBytes: 8,
    randomIdentifiers: true,
    networkPropagation: false,
  }),
  browserInstrumentation: Object.freeze({
    globalErrors: true,
    unhandledRejections: true,
    startupMeasures: true,
    navigationTimings: true,
    longTasks: true,
    paints: true,
    largestContentfulPaint: true,
    layoutShiftDeltas: true,
    pageHideFlush: true,
  }),
  transport: Object.freeze({
    defaultConfigured: false,
    defaultNetworkExport: false,
    injectable: true,
    beaconFallbackAvailable: true,
    httpsRequiredOutsideLocalDevelopment: true,
    credentials: 'omit' as const,
  }),
  compatibilityBoundaries: Object.freeze([
    Object.freeze({ id: 'vendor-export-adapter', status: 'optional-disabled-by-default' as const, reason: 'M32 provides an injectable transport and beacon/fetch adapter but does not hard-code a telemetry vendor or production endpoint.' }),
    Object.freeze({ id: 'distributed-trace-propagation', status: 'local-span-correlation-only' as const, reason: 'M32 uses W3C-sized random trace/span identifiers but does not inject trace headers into Supabase requests pending an explicit server-side trace ingestion contract.' }),
    Object.freeze({ id: 'embedded-module-observability', status: 'host-first-existing-module-diagnostics' as const, reason: 'TimeTracker, FuelTrack+, and TradeLink remain M26 compatibility islands; host telemetry captures module lifecycle diagnostics without injecting code into embedded runtimes.' }),
  ]),
  databaseChanges: Object.freeze({ migrationRequired: false, schemaChangeRequired: false, productionDataRewriteRequired: false }),
});
