export const STAGE_D_M18_VIRTUALIZATION_TARGET = Object.freeze({
  milestone: 'Stage D Milestone 18 — Virtualization',
  prerequisite: Object.freeze({ milestone: 'M17', state: 'active-certified' }),
  activationState: 'active-certified',
  architectureVersion: 27,
  virtualizationAuthority: 'src/features/boards/virtualization/board-table-virtualization.ts',
  controllerAuthority: 'assets/js/features/boards/controllers/board-table-virtualization-controller.ts',
  tableRenderer: 'assets/js/features/boards/views/table-view.ts',
  boardEngine: 'assets/js/boards-ui.ts',
  policy: Object.freeze({
    rowThreshold: 160,
    columnThreshold: 18,
    rowOverscan: 16,
    rowWindowChunk: 8,
    columnOverscanPx: 320,
  }),
  variableHeightPolicy: 'full-render-when-wrap-columns-active',
  dragPolicy: 'freeze-window-during-native-drag',
  keyboardNavigation: 'logical-grid-coordinates',
  accessibility: 'logical-aria-row-column-indices',
  tanstackTableDecision: 'defer-production-adoption',
  externalVirtualizationDependencyInstalled: false,
  noSupabaseMigration: true,
} as const);
