export type M47ActivationState = 'implementation-in-progress' | 'implementation-complete-pending-certification' | 'active-certified';

export const stageGM47BoardsTableGroupItemRecoveryTarget = Object.freeze({
  milestone: 47,
  stage: 'G',
  name: 'Boards Table / Group / Item Recovery',
  activationState: 'active-certified' as M47ActivationState,
  prerequisite: Object.freeze({ milestone: 46, requiredState: 'active-certified' as const }),
  architectureVersion: 55,
  authority: Object.freeze({
    boardController: 'assets/js/boards-ui.ts',
    selectors: 'assets/js/features/boards/selectors/board-selectors.ts',
    selection: 'assets/js/features/boards/controllers/selection-controller.ts',
    preferences: 'assets/js/features/boards/controllers/board-preference-controller.ts',
    itemWorkflows: 'assets/js/features/boards/controllers/item-workflows.ts',
    dragDrop: 'assets/js/features/boards/controllers/drag-drop-controller.ts',
    commands: 'assets/js/features/boards/services/board-command-service.ts',
    tableView: 'assets/js/features/boards/views/board-workspace-view.ts',
    migration: 'supabase/migrations/v1.43.2-stage-g-m47-boards-table-group-item-recovery.sql',
    schema: 'supabase/schema.sql',
    databaseTest: 'supabase/tests/m47/boards_table_group_item_recovery.test.sql',
    deterministicVerifier: 'scripts/verify-boards-table-group-item-recovery-execution.mjs',
    browserRunner: 'scripts/run-boards-table-group-item-recovery-browser.mjs',
    browserSpec: 'tests/modern/e2e/boards-table-group-item-recovery.spec.mjs',
    browserFixture: 'tests/modern/e2e/helpers/m47-boards-table-fixture.mjs',
    productionVerifier: 'scripts/verify-stage-g-m47-production-invariants.mjs',
  }),
  completionCriteria: Object.freeze([
    'Group creation, movement, deletion, and position compaction preserve a contiguous deterministic group order under serialized board mutations.',
    'Item creation, editing, movement, duplication, archive/restore, and deletion preserve contiguous active-item positions without partial-success UI divergence.',
    'Deleting a group containing attachment metadata fails closed so private Storage objects cannot be orphaned by a relational cascade.',
    'Shift-range selection follows rendered visible table order, excludes collapsed groups, and partial bulk failures reconcile from authoritative Board state.',
    'Keyboard navigation remains available in read-only cells and archived/custom-sorted rows suppress invalid manual-reorder affordances.',
    'Pending table preferences are snapshot-bound to the originating Board and flush across route/deactivation boundaries so sort/filter/collapse/width state persists reliably.',
    'The M46 40-RPC Board backend contract remains signature-compatible while M47 recovers mutation semantics beneath the existing API surface.',
    'Dedicated deterministic, database, browser/E2E, historical, type/build, security, artifact, and hosted certification gates pass before active-certified promotion.',
  ]),
  knownBoundaries: Object.freeze([
    'M46 remains the public Board backend contract authority; M47 changes mutation semantics without adding or removing governed Board RPC signatures.',
    'Attachment object deletion remains an explicit Storage API operation. M47 prevents group cascades while attachment metadata exists rather than attempting SQL deletion from storage.objects.',
    'M48-M53 remain responsible for later Board cell, Kanban, workspace, collaboration, and advanced relationship/formula work beyond M47 table/group/item recovery.',
    'M54 remains responsible for final production-readiness certification.',
  ]),
});
