export type M49ActivationState = 'implementation-in-progress' | 'implementation-complete-pending-certification' | 'active-certified';

export const stageGM49BoardsKanbanDragDropRecoveryTarget = Object.freeze({
  milestone: 49,
  stage: 'G',
  name: 'Boards Kanban & Drag/Drop Recovery',
  activationState: 'implementation-complete-pending-certification' as M49ActivationState,
  prerequisite: Object.freeze({ milestone: 48, requiredState: 'active-certified' as const }),
  architectureVersion: 57,
  semanticsVersion: '1.43.2-m49-v1',
  authority: Object.freeze({
    boardController: 'assets/js/boards-ui.ts',
    kanbanView: 'assets/js/features/boards/views/kanban-view.ts',
    itemDragController: 'assets/js/features/boards/controllers/drag-drop-controller.ts',
    structureDragController: 'assets/js/features/boards/controllers/structure-drag-controller.ts',
    viewSwitchController: 'assets/js/features/boards/controllers/view-switch-controller.ts',
    moveState: 'assets/js/features/boards/services/board-move-state.ts',
    historyController: 'assets/js/features/boards/controllers/history-controller.ts',
    commands: 'assets/js/features/boards/services/board-command-service.ts',
    repository: 'assets/js/features/boards/data/board-repository.ts',
    deterministicVerifier: 'scripts/verify-boards-kanban-drag-drop-recovery-execution.mjs',
    browserRunner: 'scripts/run-boards-kanban-drag-drop-recovery-browser.mjs',
    browserSpec: 'tests/modern/e2e/boards-kanban-drag-drop-recovery.spec.mjs',
    browserFixture: 'tests/modern/e2e/helpers/m49-boards-kanban-fixture.mjs',
    retainedBackendContract: 'config/stage-g-m46-board-backend-contract.ts',
    retainedTableAuthority: 'config/stage-g-m47-boards-table-group-item-recovery-target.ts',
    retainedTypedCellAuthority: 'config/stage-g-m48-boards-columns-cells-status-recovery-target.ts',
  }),
  backendBoundary: Object.freeze({
    mode: 'retained-m46-m47-no-schema-change-v1' as const,
    migrationRequired: false,
    newRpcRequired: false,
    rlsChangeRequired: false,
    rationale: 'M49 recovers Kanban/view-switch/client drag transaction semantics using the existing governed Board move/view RPCs already certified by M46-M48.',
  }),
  completionCriteria: Object.freeze([
    'Kanban renders every canonical visible item exactly once, including retained references to inactive or unavailable statuses, without allowing new drops into non-active lanes.',
    'Pure Kanban status movement changes status only and never changes the item group or Table position as a hidden side effect.',
    'Table item, group, and column movement remains deterministic and rollback-safe when persistence fails.',
    'Undo and redo movement callbacks restore the last confirmed local snapshot when their persistence operation fails.',
    'Table/Kanban view switching serializes persistence, restores the last confirmed view on failure, and prevents stale asynchronous completions from overriding the latest intent.',
    'Keyboard-accessible alternatives exist for Kanban lane movement, Table item reorder, group reorder, and column reorder with focus restoration and live announcements.',
    'Dedicated deterministic and browser/E2E authorities prove canonical-state preservation across drag/drop, rollback, reload, and Table/Kanban transitions.',
    'Fail-closed exact-commit certification, post-state regression, package hygiene, hosted verification, and certified artifact publication pass before active-certified promotion.',
  ]),
  knownBoundaries: Object.freeze([
    'M19 remains the architectural decision authority for product-owned/native Board drag interaction; M49 does not introduce dnd-kit or another drag library.',
    'M46/M47 remain the backend schema/RPC/RLS and table/group/item ordering authorities; M48 remains the typed column/cell/status authority. M49 intentionally adds no database migration, RPC, grant, or RLS policy.',
    'The TypeScript assets/js Boards runtime remains behind the React Board presentation facade; M49 does not perform a React Kanban rewrite.',
    'M50-M53 remain responsible for later Board recovery scopes, and M54 remains final production-readiness certification.',
  ]),
});
