export const stageIM96VisualConsistencyLegacyStylingRetirementTarget = Object.freeze({
  milestone: 96,
  stage: 'I',
  release: '1.43.2',
  name: 'Visual Consistency & Legacy Styling Retirement',
  semanticsVersion: '1.43.2-m96-v1',
  activationState: 'active-certified',
  failClosed: true,
  prerequisite: Object.freeze({
    milestone: 95,
    certifiedZipSha256: '25c15f1e4c81d97adfcc5ba2e309a87887ed060ffb52904eea9214e8ff4bf4a7',
    certifiedSourceSha256: '995dba51a9d4165b3b090487917f21c8c6651dc461716e972c89e1ae840cca6c',
  }),
  scope: Object.freeze([
    'retire-stage-h-one-off-styling-bridges',
    'consolidate-live-rules-into-stage-i-successor-authorities',
    'remove-transitional-harmonization-presentation-markers',
    'remove-provably-unused-custom-properties',
    'preserve-visual-and-runtime-semantics',
    'synchronize-historical-regression-verifiers',
    'prevent-retired-path-reintroduction',
  ]),
  retiredStyleLayers: Object.freeze([
    'assets/css/foundation/host-ui-migration.css',
    'assets/css/foundation/boards-ui-migration.css',
    'apps/time-tracker/m74-harmonization.css',
    'apps/fueltrack-plus/m75-harmonization.css',
    'apps/tradelink/m76-harmonization.css',
  ]),
  retiredTransitionalMarkers: Object.freeze([
    'wmTimeTrackerHarmonized/data-wm-time-tracker-harmonized',
    'wmFuelTrackHarmonized/data-wm-fueltrack-harmonized',
    'wmTradeLinkHarmonized/data-wm-tradelink-harmonized',
  ]),
  retiredUnusedCustomProperties: Object.freeze([
    '--m85-tt-gap-xs',
    '--m85-tt-gap-sm',
    '--m87-tl-raised',
    '--wm-m95-responsive-inline-gutter',
  ]),
  baselineCss: Object.freeze({ files: 47, sourceBytes: 1202209 }),
  boundaries: Object.freeze({
    noDatabaseSchemaMutation: true,
    noMigrationMutation: true,
    noBackendApiMutation: true,
    noAuthenticationAuthorizationMutation: true,
    noPersistenceMutation: true,
    noRouteOwnershipMutation: true,
    noModuleBusinessLogicMutation: true,
    noBehavioralFeatureRemoval: true,
  }),
  outputDirectory: 'm96-continuation-artifacts-upload',
  continuationBaseline: 'Work-Management-App-v1.43.2-Stage-I-M96-Implementation-Complete-Verification-Pending.zip',
} as const);
