export const STAGE_H_M56_UI_ARCHITECTURE_INVENTORY_TARGET = Object.freeze({
  milestone: 56,
  stage: 'H',
  release: '1.43.2',
  semanticsVersion: '1.43.2-m56-v1',
  scope: 'ui-architecture-inventory-design-governance-baseline',
  activationState: 'active-certified',
  failClosed: true,
  canonicalInventory: 'config/ui-architecture-inventory.ts',
  baselineSnapshot: 'regression-baseline/m56-ui-architecture-inventory.json',
  governanceDocumentation: 'architecture/ui-governance/README.md',
  requiredStaticGate: 'ui-inventory:check',
  requiredDeterministicGate: 'ui-inventory:test',
  requiredBrowserGate: 'ui-inventory:browser',
  requiredCertificationGate: 'ui-inventory:certify',
  requiredHistoricalGate: 'verify:historical-all',
  certifiedArtifactDirectory: 'm56-certified-artifacts-upload',
  certifiedBaseline: 'Work-Management-App-v1.43.2-Stage-H-M56-Certified-Baseline.zip',
  visualRuntimeMutationAllowed: false,
} as const);
