export type M48ActivationState = 'implementation-in-progress' | 'implementation-complete-pending-certification' | 'active-certified';

export const stageGM48BoardsColumnsCellsStatusRecoveryTarget = Object.freeze({
  milestone: 48,
  stage: 'G',
  name: 'Boards Columns, Cells & Status System Recovery',
  activationState: 'active-certified' as M48ActivationState,
  prerequisite: Object.freeze({ milestone: 47, requiredState: 'active-certified' as const }),
  architectureVersion: 56,
  authority: Object.freeze({
    boardController: 'assets/js/boards-ui.ts',
    columnWorkflows: 'assets/js/features/boards/controllers/column-workflows.ts',
    inlineEditor: 'assets/js/features/boards/controllers/inline-edit-controller.ts',
    resizeController: 'assets/js/features/boards/controllers/column-resize-controller.ts',
    structureDragController: 'assets/js/features/boards/controllers/structure-drag-controller.ts',
    selectors: 'assets/js/features/boards/selectors/board-selectors.ts',
    statusLabels: 'assets/js/features/boards/status-labels.ts',
    statusEditor: 'assets/js/features/boards/services/status-label-editor.ts',
    columnTypeRegistry: 'assets/js/features/boards/grid/column-type-registry.ts',
    editorContracts: 'src/features/boards/contracts/editor.ts',
    repository: 'assets/js/features/boards/data/board-repository.ts',
    commands: 'assets/js/features/boards/services/board-command-service.ts',
    deterministicVerifier: 'scripts/verify-boards-columns-cells-status-recovery-execution.mjs',
    browserRunner: 'scripts/run-boards-columns-cells-status-recovery-browser.mjs',
    browserSpec: 'tests/modern/e2e/boards-columns-cells-status-recovery.spec.mjs',
    browserFixture: 'tests/modern/e2e/helpers/m48-boards-columns-fixture.mjs',
    retainedBackendContract: 'config/stage-g-m46-board-backend-contract.ts',
    retainedProductionVerifier: 'scripts/verify-stage-g-m47-production-invariants.mjs',
  }),
  backendBoundary: Object.freeze({
    mode: 'retained-m46-m47-no-schema-change-v1' as const,
    migrationRequired: false,
    newRpcRequired: false,
    rlsChangeRequired: false,
    rationale: 'M48 restores client typed-column/cell/status lifecycle semantics against Board RPCs and database validators already governed by M46/M47.',
  }),
  completionCriteria: Object.freeze([
    'Columns can be added, renamed, reordered, resized with rollback-safe pointer cancellation, duplicated, type-changed, and permanently removed without stale preference references.',
    'Text, Status, Person, Date, Dropdown, and Numeric cell editors normalize values by type, preserve explicit save/cancel semantics, and persist through the authoritative Board RPC boundary.',
    'Status and Dropdown filtering uses exact typed choice equality while textual filters remain case-insensitive substring matching.',
    'Typed sorting remains deterministic and keeps empty values last in both ascending and descending directions.',
    'Status-label lifecycle supports add, rename, reorder, activate/deactivate, delete, default assignment, validation, atomic persistence, and clearing of references to removed labels.',
    'Dropdown configuration enforces one to fifty case-insensitively unique options with the same defaults and size limits as the existing database contract.',
    'Dedicated deterministic and browser/E2E workflows prove interaction, persistence, reload, cancellation, preference cleanup, and retained M47/M46 regressions.',
    'Fail-closed certification, post-certification regression, checksum/package hygiene, exact-commit provenance, hosted verification, and certified artifact publication pass before active-certified promotion.',
  ]),
  knownBoundaries: Object.freeze([
    'M46/M47 remain the backend schema/RPC/RLS authority; M48 intentionally adds no migration, RPC, grant, or RLS policy because existing server contracts already support the recovered semantics.',
    'The typed Board interaction engine remains assets/js/boards-ui.ts behind the React Board presentation facade. M48 does not expand scope into a React rewrite of the Board grid.',
    'M49-M53 remain responsible for later Kanban, item-workspace, collaboration, relationship/formula, and other Board recovery areas outside M48.',
    'M54 remains responsible for final production-readiness certification after all Stage G Board recovery milestones complete.',
  ]),
});
