export type M30ActivationState =
  | 'implementation-complete-pending-certification'
  | 'active-pending-release-certification'
  | 'active-certified';

export const stageFM30ModernTestingStackTarget = Object.freeze({
  milestone: 30,
  stage: 'F',
  name: 'Modern testing stack',
  activationState: 'active-certified' as M30ActivationState,
  prerequisite: Object.freeze({ milestone: 29, requiredState: 'active-certified' as const }),
  architectureVersion: 38,
  authority: Object.freeze({
    runner: 'vitest-5' as const,
    e2eRunner: 'playwright-1.63' as const,
    domEnvironment: 'jsdom-27' as const,
    reactTesting: 'testing-library-react-16' as const,
    interactionTesting: 'testing-library-user-event-14' as const,
    domAssertions: 'testing-library-jest-dom-7' as const,
    coverageProvider: 'vitest-v8-coverage-5' as const,
    testRoot: 'tests/modern',
    config: 'vitest.config.mjs',
    runnerScript: 'scripts/run-modern-tests.mjs',
    bootstrapScript: 'scripts/ensure-modern-test-toolchain.mjs',
    e2eConfig: 'playwright.config.mjs',
    e2eRunnerScript: 'scripts/run-modern-browser-tests.mjs',
    verifier: 'verify-stage-f-m30-modern-testing-stack.mjs',
  }),
  pinnedTools: Object.freeze({
    vitest: '5.0.0',
    coverageV8: '5.0.0',
    testingLibraryDom: '10.4.1',
    testingLibraryReact: '16.3.3',
    testingLibraryUserEvent: '14.6.7',
    testingLibraryJestDom: '7.0.1',
    jsdom: '27.4.0',
    jsdomNodeEngine: '^20.19.0 || ^22.12.0 || >=24.0.0',
    playwright: '1.63.0',
  }),
  baseline: Object.freeze({
    testFiles: 5,
    testCases: 23,
    assertionExpressions: 74,
    layers: Object.freeze(['unit', 'component', 'e2e']),
    subjects: Object.freeze([
      'route policy authorization/navigation decisions',
      'Board row/column virtualization planning',
      'Zustand shell client-state ownership semantics',
      'React design-system button accessibility and interaction',
      'real Work Management login composition ownership through Playwright',
    ]),
  }),
  coverage: Object.freeze({
    provider: 'v8' as const,
    statements: 75,
    branches: 65,
    functions: 75,
    lines: 75,
    reportsDirectory: 'coverage/modern',
    releaseGateRequired: true,
  }),
  execution: Object.freeze({
    testCommand: 'npm run modern-tests:test',
    coverageCommand: 'npm run modern-tests:coverage',
    e2eCommand: 'npm run modern-tests:e2e',
    packageManifestImmutableDuringBootstrap: true,
    applicationLockfileImmutableDuringBootstrap: true,
    installScriptsDisabledForEphemeralTooling: true,
    exactTopLevelTestingVersionsRequired: true,
  }),
  compatibilityBoundaries: Object.freeze([
    Object.freeze({ id: 'legacy-cdp-browser-harness', status: 'retained-parity-backstop' as const, reason: 'M30 introduces Playwright as the modern application browser-test authority but retains the certified bounded-CDP harness as a release parity backstop until a later explicit retirement milestone proves equivalent or broader browser coverage.' }),
    Object.freeze({ id: 'database-rls-pgtap', status: 'independent-specialized-suite' as const, reason: 'M29 pgTAP remains the authoritative database/RLS test layer; Vitest does not replace transactional PostgreSQL authorization testing.' }),
    Object.freeze({ id: 'isolated-test-toolchain', status: 'exact-ephemeral-bootstrap' as const, reason: 'The application package-lock remains the production dependency authority. M30 testing tools are exact-pinned and installed with --no-save --package-lock=false; the runner verifies package.json and package-lock.json are unchanged.' }),
    Object.freeze({ id: 'embedded-module-browser-contracts', status: 'existing-verifiers-retained' as const, reason: 'TimeTracker, FuelTrack+, and TradeLink retain their existing stabilization/release verifiers and same-origin compatibility boundaries; M30 adds representative host-platform tests rather than rewriting embedded module test suites.' }),
  ]),
  dependencyChanges: Object.freeze({ applicationRuntimeDependencyAdded: false, applicationPackageLockChangeRequired: false, ephemeralTestToolchainAdded: true }),
  databaseChanges: Object.freeze({ migrationRequired: false, schemaChangeRequired: false, productionDataRewriteRequired: false }),
});
