import { test, expect } from '@playwright/test';
const email=process.env.WM_M54_E2E_ADMIN_EMAIL||'';
const password=process.env.WM_M54_E2E_ADMIN_PASSWORD||'';
const productionUrl=(process.env.WM_PLAYWRIGHT_BASE_URL||'').replace(/\/?$/,'/');
const liveUrl=(hash)=>new URL(hash,productionUrl).href;
const go=async(page,route)=>page.evaluate((r)=>{location.hash=`#/${r}`;},route);
test('@m54-live authenticated production administrator can traverse certified host and module workflows',async({page})=>{
  await page.goto(liveUrl('#/login'));
  const form=page.locator('form[data-auth-form="login"]');
  await expect(form).toBeVisible();
  await form.locator('input[name="email"]').fill(email);
  await form.locator('input[name="password"]').fill(password);
  await form.getByRole('button',{name:'Sign in'}).click();
  await expect(form).toBeHidden({timeout:20000});
  await go(page,'account');
  await expect(page.locator('[data-wm-management-view="account"]')).toBeVisible({timeout:20000});
  await expect(page.locator('[data-wm-management-view="account"]')).toContainText(email,{ignoreCase:true});
  await go(page,'settings');
  await expect(page.locator('[data-wm-management-view="settings"]')).toBeVisible();
  await go(page,'users');
  await expect(page.locator('[data-wm-management-view="users"]')).toBeVisible();
  await go(page,'boards');
  await expect(page.getByRole('heading',{name:'Boards',level:1})).toBeVisible();
  for(const moduleId of ['time-tracker','fueltrack-plus','tradelink']){
    await go(page,`app/${moduleId}`);
    const frame=page.locator('#moduleFrame');
    await expect(frame).toBeVisible({timeout:15000});
    await page.waitForFunction((id)=>globalThis.WorkManagementRuntime?.getContext?.()?.moduleId===id,moduleId);
    const hostContext=await page.evaluate(()=>globalThis.WorkManagementRuntime?.getContext?.());
    expect(hostContext?.moduleId).toBe(moduleId);
    expect(hostContext?.authenticated).toBe(true);
    const frameHandle=await frame.elementHandle();
    expect(frameHandle).toBeTruthy();
    const moduleFrame=await frameHandle.contentFrame();
    expect(moduleFrame).toBeTruthy();
    await moduleFrame.waitForFunction((id)=>globalThis.WM_IDENTITY_CONTEXT?.moduleId===id&&globalThis.WM_MODULE_ACCESS?.moduleId===id,moduleId);
    const identity=await moduleFrame.evaluate(()=>globalThis.WM_IDENTITY_CONTEXT);
    const access=await moduleFrame.evaluate(()=>globalThis.WM_MODULE_ACCESS);
    expect(identity?.accountStatus).toBe('active');
    expect(identity?.module?.enabled).toBe(true);
    expect(identity?.module?.role).toBeTruthy();
    expect(access?.allowed).toBe(true);
    expect(access?.role).toBe(identity?.module?.role);
  }
});
