import { test, expect } from '@playwright/test';
test('M83 authentication and account visual system is responsive without hiding functional controls', async ({page})=>{
  await page.setViewportSize({width:1366,height:820}); await page.goto('/'); await page.waitForLoadState('domcontentloaded');
  await page.evaluate(()=>{const host=document.createElement('div');host.id='m83-fixture';host.innerHTML=`<div class="auth-shell wm-identity-surface"><main class="auth-panel wm-identity-panel"><header class="wm-identity-panel-header"><span class="auth-kicker">SECURE ACCESS</span><h1>Sign in to your workspace</h1><p class="wm-identity-description">Cloud identity</p></header><div class="wm-identity-panel-body"><form class="auth-form"><label>Email<input id="m83-email" type="email"></label><label>Password<input id="m83-password" type="password"></label><button id="m83-submit" class="primary-btn">Sign in</button></form><div class="auth-message warning">Confirmation required</div></div></main></div><main class="page account-page wm-account-surface"><section class="settings-card wm-account-section"><div class="settings-row"><div><span>IDENTITY</span><h2>Example User</h2><p>user@example.test</p></div><button id="m83-account-action" class="secondary-btn">Refresh session & access</button></div></section></main>`;document.body.append(host)});
  const desktop=await page.evaluate(()=>{const panel=document.querySelector('.wm-identity-panel'),action=document.querySelector('#m83-submit');return{panelWidth:panel.getBoundingClientRect().width,display:getComputedStyle(action).display,overflow:Math.max(document.documentElement.scrollWidth-document.documentElement.clientWidth,0)}});
  expect(desktop.panelWidth).toBeGreaterThan(300); expect(desktop.display).not.toBe('none'); expect(desktop.overflow).toBe(0);
  await page.setViewportSize({width:390,height:844});
  const mobile=await page.evaluate(()=>{const panel=document.querySelector('.wm-identity-panel'),account=document.querySelector('.wm-account-section'),button=document.querySelector('#m83-account-action');return{panelWidth:panel.getBoundingClientRect().width,accountWidth:account.getBoundingClientRect().width,buttonDisplay:getComputedStyle(button).display,overflow:Math.max(document.documentElement.scrollWidth-document.documentElement.clientWidth,0)}});
  expect(mobile.panelWidth).toBeLessThanOrEqual(390); expect(mobile.accountWidth).toBeLessThanOrEqual(390); expect(mobile.buttonDisplay).not.toBe('none'); expect(mobile.overflow).toBe(0);
});
