import fs from 'node:fs';import path from 'node:path';import { test, expect } from '@playwright/test';
import {assertFrameNoHorizontalOverflow,assertNoHorizontalOverflow,installM53Admin,waitForEmbeddedIdentity,waitForM39Identity} from './helpers/m53-hardening-fixture.mjs';
const evidenceDir=process.env.WM_M97_EVIDENCE_DIR;if(!evidenceDir)throw new Error('WM_M97_EVIDENCE_DIR is required');
const viewports=[{id:'mobile',width:390,height:844},{id:'tablet',width:768,height:1024},{id:'laptop',width:1366,height:768},{id:'desktop',width:1440,height:900}];
const hostRoutes=['account','settings','users','boards'];const moduleRole={'time-tracker':'System Admin','fueltrack-plus':'Admin',tradelink:'General Manager'};
const shot=async(page,testInfo,viewport,surface)=>{const dir=path.join(evidenceDir,testInfo.project.name,viewport);fs.mkdirSync(dir,{recursive:true});await page.screenshot({path:path.join(dir,`${surface}.png`),fullPage:true,animations:'disabled'});};
async function bootstrap(page){await installM53Admin(page);await page.goto('/#/account');await waitForM39Identity(page,{role:'admin_general_manager'});}
for(const vp of viewports){
 test(`@m97-visual host workspace ${vp.id} visual contracts and screenshots`,async({page},testInfo)=>{await page.setViewportSize({width:vp.width,height:vp.height});const errors=[];page.on('pageerror',e=>errors.push(e.message));await bootstrap(page);for(const route of hostRoutes){await page.evaluate(r=>{location.hash=`#/${r}`},route);if(route==='boards')await expect(page.getByRole('heading',{name:'Boards',level:1})).toBeVisible();else await expect(page.locator(`[data-wm-management-view="${route}"]`)).toBeVisible();await assertNoHorizontalOverflow(page,4);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth+4)).toBe(true);await shot(page,testInfo,vp.id,`host-${route}`);}expect(errors).toEqual([]);});
 test(`@m97-visual embedded modules ${vp.id} visual contracts and screenshots`,async({page},testInfo)=>{await page.setViewportSize({width:vp.width,height:vp.height});const errors=[];page.on('pageerror',e=>errors.push(e.message));await bootstrap(page);for(const [moduleId,role] of Object.entries(moduleRole)){await page.evaluate(id=>{location.hash=`#/app/${id}`},moduleId);const identity=await waitForEmbeddedIdentity(page,moduleId,role);expect(identity.module.role).toBe(role);await assertNoHorizontalOverflow(page,4);await assertFrameNoHorizontalOverflow(page,moduleId,6,2500);await shot(page,testInfo,vp.id,`module-${moduleId}`);}expect(errors).toEqual([]);});
}
test('@m97-functional authenticated behavior/ownership survives visual migration',async({page})=>{await bootstrap(page);for(const route of hostRoutes){await page.evaluate(r=>{location.hash=`#/${r}`},route);if(route==='boards')await expect(page.getByRole('heading',{name:'Boards',level:1})).toBeVisible();else await expect(page.locator(`[data-wm-management-view="${route}"]`)).toBeVisible();expect(await locationHash(page)).toBe(`#/${route}`);}for(const [moduleId,role] of Object.entries(moduleRole)){await page.evaluate(id=>{location.hash=`#/app/${id}`},moduleId);const identity=await waitForEmbeddedIdentity(page,moduleId,role);expect(identity.module.enabled).toBe(true);expect(identity.module.role).toBe(role);}});
async function locationHash(page){return page.evaluate(()=>location.hash)}
