#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)";cd "$ROOT"
printf '\n%s\n' '============================================================' 'M97 LOCAL CERTIFICATION — ENVIRONMENT PREPARATION' '============================================================';[ "$(node --version)" = 'v22.16.0' ] || { echo 'FAIL: Node v22.16.0 required.' >&2; exit 1; };[ "$(npm --version)" = '10.9.2' ] || { echo 'FAIL: npm 10.9.2 required.' >&2; exit 1; };rm -rf node_modules dist coverage test-results playwright-report .wm-modern-test-toolchain m97-browser-evidence
printf '\n%s\n' '============================================================' 'WORKSPACE / REPOSITORY VALIDATION' '============================================================';test -f package.json;test -f package-lock.json;test -f config/stage-i-m97-workspace-wide-visual-regression-functional-preservation-target.ts;npm run workspace-regression:source-guard;node scripts/verify-stage-i-m96-m95-source-guard.mjs;npm run token-theme:source-guard
printf '\n%s\n' '============================================================' 'DEPENDENCY INSTALLATION + INTEGRITY' '============================================================';npm ci;npm run dependencies:verify-lockfile;npm ls --depth=0
printf '\n%s\n' '============================================================' 'STATIC VERIFICATION' '============================================================';npm run workspace-regression:check;npm run typecheck;npm run lint:eslint;npm run build
printf '\n%s\n' '============================================================' 'DETERMINISTIC AUTOMATED TESTS' '============================================================';npm run workspace-regression:test;npm run functional-regression:check;npm run functional-regression:test;npm run cross-module-rbac-e2e:check;npm run timetracker-stabilization:check;npm run fueltrack-stabilization:check;npm run tradelink-stabilization:check
printf '\n%s\n' '============================================================' 'BROWSER / E2E + SCREENSHOT EVIDENCE GATE' '============================================================';npm run workspace-regression:browser;npm run workspace-regression:evidence
printf '\n%s\n' '============================================================' 'DEDICATED CERTIFICATION' '============================================================';npm run workspace-regression:certify
printf '\n%s\n' '============================================================' 'POST-CERTIFICATION STATE VALIDATION' '============================================================';npm run workspace-regression:post-certification
printf '\n%s\n' '============================================================' 'HISTORICAL REGRESSION GATE' '============================================================';npm run verify:historical-all;npm run release:check
printf '\n%s\n' '============================================================' 'CHECKSUM + PACKAGE HYGIENE' '============================================================';npm run workspace-regression:package-hygiene
printf '\n%s\n' '============================================================' 'FINAL CHECKPOINT VALIDATION' '============================================================';npm run workspace-regression:final-checkpoint
printf '\n%s\n' '============================================================' 'PUBLISH CERTIFIED M97 BASELINE' '============================================================';npm run workspace-regression:publish-certified
printf '\n%s\n' '============================================================' 'ALL REQUIRED M97 IMPLEMENTATION AND CERTIFICATION WORK PASSED' '============================================================'
