import { HEADER_ALIAS_MAP, IMPORT_FIELD_BY_KEY, MATERIAL_IMPORT_FIELDS, REQUIRED_IMPORT_KEYS, groupIdFromValue, normalizeHeader } from './material-import-spec.js';

const MAX_FILE_ROWS = 5000;
const MAX_COMMIT_ROWS = 1000;
const BLANK = (v) => v == null || String(v).trim() === '';

export const IMPORT_STATUS = Object.freeze({ VALID:'valid', INVALID:'invalid', DUPLICATE:'duplicate', CONFLICT:'conflicting', SKIPPED:'skipped' });

export function detectHeaderRow(matrix, { scanRows = 25 } = {}) {
  let best={index:-1,score:-1,matches:0}; const limit=Math.min(matrix.length,scanRows);
  for(let i=0;i<limit;i++){const row=matrix[i]||[];let score=0,matches=0;const seen=new Set();for(const value of row){const key=HEADER_ALIAS_MAP.get(normalizeHeader(value));if(key&&!seen.has(key)){seen.add(key);matches++;score+=IMPORT_FIELD_BY_KEY[key]?.required?4:1;}}if(matches>=2&&score>best.score)best={index:i,score,matches};}
  if(best.index<0) throw new Error('No recognizable header row was found in the first 25 rows.'); return best;
}

export function suggestColumnMapping(headers) { const mapping={}; headers.forEach((h,index)=>{const key=HEADER_ALIAS_MAP.get(normalizeHeader(h));if(key&&mapping[key]==null)mapping[key]=index;}); return mapping; }

export function validateMapping(mapping) {
  const errors=[]; const used=new Map();
  for(const [key,index] of Object.entries(mapping||{})){if(index==null||index==='')continue;if(!IMPORT_FIELD_BY_KEY[key])errors.push({field:key,code:'unknown_field',message:`Unknown import field: ${key}`});const n=Number(index);if(!Number.isInteger(n)||n<0)errors.push({field:key,code:'invalid_column',message:`Invalid column index for ${key}.`});if(used.has(n))errors.push({field:key,code:'duplicate_mapping',message:`Column is already mapped to ${used.get(n)}.`});else used.set(n,key);}
  for(const key of REQUIRED_IMPORT_KEYS)if(mapping?.[key]==null)errors.push({field:key,code:'required_mapping',message:`${IMPORT_FIELD_BY_KEY[key].column} must be mapped.`});
  return errors;
}

function parseNumber(value, spec, integer=false){if(BLANK(value))return {value:null};let text=String(value).trim().replace(/\s/g,'');if(/^\([^()]+\)$/.test(text))text='-'+text.slice(1,-1);text=text.replace(/(?<=\d),(?=\d{3}(?:\D|$))/g,'');if(!/^[-+]?(?:\d+\.?\d*|\.\d+)(?:[eE][-+]?\d+)?$/.test(text))return {error:'must be a valid number'};const n=Number(text);if(!Number.isFinite(n))return {error:'must be finite'};if(integer&&!Number.isInteger(n))return {error:'must be a whole number'};if(spec.min!=null&&n<spec.min)return {error:`must be at least ${spec.min}`};if(spec.max!=null&&n>spec.max)return {error:`must be no more than ${spec.max}`};return {value:n};}
function excelSerialToIso(n){const whole=Math.floor(n);const adj=whole>59?whole-1:whole;return new Date(Date.UTC(1899,11,31)+adj*86400000).toISOString().slice(0,10);}
function parseDate(value){if(BLANK(value))return {value:null};if(typeof value==='number'||/^\d+(?:\.\d+)?$/.test(String(value).trim())){const n=Number(value);if(n>0&&n<300000)return {value:excelSerialToIso(n)};}const s=String(value).trim();let m=s.match(/^(\d{4})-(\d{2})-(\d{2})(?:[T\s].*)?$/);if(m){const d=new Date(`${m[1]}-${m[2]}-${m[3]}T00:00:00Z`);if(!Number.isNaN(d.valueOf())&&d.toISOString().slice(0,10)===`${m[1]}-${m[2]}-${m[3]}`)return {value:`${m[1]}-${m[2]}-${m[3]}`};return {error:'contains an invalid calendar date'};}m=s.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);if(m){const iso=`${m[3]}-${m[1].padStart(2,'0')}-${m[2].padStart(2,'0')}`;return parseDate(iso);}const d=new Date(s);if(!Number.isNaN(d.valueOf()))return {value:d.toISOString().slice(0,10)};return {error:'must be a recognized date, preferably YYYY-MM-DD'};}
function parseReferences(value,spec){if(BLANK(value))return {value:[]};const tokens=String(value).split(';').map(x=>x.trim()).filter(Boolean);if(tokens.length>(spec.maxItems||50))return {error:`supports at most ${spec.maxItems||50} references`};const linkedItems=[];for(const token of tokens){const [rawId,...rest]=token.split('|');const hasPipe=token.includes('|');const id=hasPipe?rawId.trim():'';const name=(hasPipe?rest.join('|'):rawId).trim();if(!name)return {error:'contains a relationship reference without a name'};if(id.length>(spec.maxLength||200)||name.length>(spec.maxLength||200))return {error:`contains a reference longer than ${spec.maxLength||200} characters`};linkedItems.push(id?{id,name}:{name});}return {value:linkedItems};}
function normalizeValue(raw,spec){if(BLANK(raw)){if(spec.required)return {error:'is required'};return {value:spec.default??null};}if(spec.type==='string'||spec.type==='identifier'){const value=String(raw).trim();if(spec.maxLength&&value.length>spec.maxLength)return {error:`must be ${spec.maxLength} characters or fewer`};if(spec.type==='identifier'&&!/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/.test(value))return {error:'contains unsupported identifier characters'};return {value};}if(spec.type==='number')return parseNumber(raw,spec,false);if(spec.type==='integer')return parseNumber(raw,spec,true);if(spec.type==='date')return parseDate(raw);if(spec.type==='enum'){let value=String(raw).trim();if(spec.key==='groupId'){const group=groupIdFromValue(value);if(!group)return {error:`must be one of: ${spec.values.join(', ')}`};return {value:group};}if(spec.key==='currency'||spec.key==='shippingCostCurrency')value=value.toUpperCase();else if(spec.key==='sourceType')value=value.charAt(0).toUpperCase()+value.slice(1).toLowerCase();if(!spec.values.includes(value))return {error:`must be one of: ${spec.values.join(', ')}`};return {value};}if(spec.type==='references')return parseReferences(raw,spec);return {value:raw};}

function canonicalPayload(values){const payload={sourceType:values.sourceType,materialDescription:values.materialDescription,brand:values.brand,quantity:values.quantity,buyingPrice:values.buyingPrice,currency:values.currency};for(const key of ['shippingCost','shippingCostCurrency','leadtimeInWeeks','dateRequired','rfqRefNo','vendorDetails'])if(values[key]!=null&&values[key]!=='')payload[key]=values[key];if(values.accountRefs?.length)payload.accounts={linkedItems:values.accountRefs};if(values.supplierPoRefs?.length)payload.supplierPoNo={linkedItems:values.supplierPoRefs};return payload;}

export function validateAndNormalizeRows(matrix, headerIndex, mapping, { excluded = new Set() } = {}) {
  if(matrix.length>MAX_FILE_ROWS+headerIndex+1)throw new Error(`Import contains more than ${MAX_FILE_ROWS} data rows.`);const mappingErrors=validateMapping(mapping);if(mappingErrors.length)return {rows:[],mappingErrors,summary:{valid:0,invalid:0,duplicate:0,conflicting:0,skipped:0}};
  const rows=[];const seenNames=new Map(),seenIds=new Map();
  for(let i=headerIndex+1;i<matrix.length;i++){const source=matrix[i]||[];const rowNumber=i+1;if(source.every(BLANK)){rows.push({rowNumber,status:IMPORT_STATUS.SKIPPED,selected:false,errors:[],warnings:[],raw:source});continue;}if(excluded.has(rowNumber)){rows.push({rowNumber,status:IMPORT_STATUS.SKIPPED,selected:false,errors:[],warnings:[],raw:source});continue;}const values={},errors=[],warnings=[];
    for(const spec of MATERIAL_IMPORT_FIELDS){const col=mapping[spec.key];const raw=col==null?null:source[col];const n=normalizeValue(raw,spec);if(n.error)errors.push({field:spec.key,column:spec.column,code:'invalid_value',message:`${spec.column} ${n.error}.`,value:raw});else values[spec.key]=n.value;}
    if(values.shippingCost!=null&&values.shippingCostCurrency==null)values.shippingCostCurrency='PHP';
    let status=errors.length?IMPORT_STATUS.INVALID:IMPORT_STATUS.VALID;const nameKey=String(values.name||'').trim().toLowerCase();const idKey=String(values.id||'').trim();
    if(!errors.length&&nameKey){if(seenNames.has(nameKey)){status=IMPORT_STATUS.DUPLICATE;errors.push({field:'name',column:'Part Number',code:'duplicate_in_file',message:`Duplicate Part Number in import file (also row ${seenNames.get(nameKey)}).`});}else seenNames.set(nameKey,rowNumber);}
    if(!errors.length&&idKey){if(seenIds.has(idKey)){status=IMPORT_STATUS.DUPLICATE;errors.push({field:'id',column:'Material ID',code:'duplicate_id_in_file',message:`Duplicate Material ID in import file (also row ${seenIds.get(idKey)}).`});}else seenIds.set(idKey,rowNumber);}
    rows.push({rowNumber,status,selected:status===IMPORT_STATUS.VALID,errors,warnings,values,canonical:{id:values.id||null,name:values.name||'',groupId:values.groupId,payload:canonicalPayload(values)},raw:source});}
  return {rows,mappingErrors:[],summary:summarizeRows(rows)};
}

export function applyServerPreflight(rows, serverResult) { const byRow=new Map((serverResult?.rows||[]).map(r=>[Number(r.rowNumber),r]));return rows.map(row=>{if(row.status!==IMPORT_STATUS.VALID || !row.selected)return row;const s=byRow.get(row.rowNumber);if(!s)return {...row,status:IMPORT_STATUS.CONFLICT,selected:false,errors:[...row.errors,{code:'missing_preflight',message:'Server preflight did not return this row.'}]};if(s.status==='valid')return {...row,serverAction:s.action||'create',existingId:s.existingId||null};return {...row,status:s.status||IMPORT_STATUS.CONFLICT,selected:false,existingId:s.existingId||null,errors:[...row.errors,{code:s.code||'server_conflict',message:s.message||'Server preflight conflict.'}]};}); }
export function summarizeRows(rows){const s={valid:0,invalid:0,duplicate:0,conflicting:0,skipped:0,total:rows.length,selected:0};for(const r of rows){if(r.status===IMPORT_STATUS.CONFLICT)s.conflicting++;else if(r.status===IMPORT_STATUS.DUPLICATE)s.duplicate++;else if(r.status===IMPORT_STATUS.INVALID)s.invalid++;else if(r.status===IMPORT_STATUS.SKIPPED)s.skipped++;else s.valid++;if(r.selected)s.selected++;}return s;}
export function rowsForCommit(rows){const selected=rows.filter(r=>r.selected&&r.status===IMPORT_STATUS.VALID);if(selected.length>MAX_COMMIT_ROWS)throw new Error(`A single atomic commit is limited to ${MAX_COMMIT_ROWS} rows.`);return selected.map(r=>({rowNumber:r.rowNumber,...r.canonical}));}
export const IMPORT_LIMITS=Object.freeze({maxFileRows:MAX_FILE_ROWS,maxCommitRows:MAX_COMMIT_ROWS,maxFileBytes:10*1024*1024});
